// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiM8TKzMB2P3-DftAqoShZA-FFiGXlEw',
    appId: '1:144754486345:web:f7646403f7051a8fd5a398',
    messagingSenderId: '144754486345',
    projectId: 'social-app-d5767',
    authDomain: 'social-app-d5767.firebaseapp.com',
    storageBucket: 'social-app-d5767.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVrtQ5OBft8xa9Q-YYpeGP_RnkWWVdoMQ',
    appId: '1:144754486345:android:945a9710f3899592d5a398',
    messagingSenderId: '144754486345',
    projectId: 'social-app-d5767',
    storageBucket: 'social-app-d5767.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJkG7-5I4kzEpyLGhYMCdvbgNl9MTYAE',
    appId: '1:144754486345:ios:b961187b331133e2d5a398',
    messagingSenderId: '144754486345',
    projectId: 'social-app-d5767',
    storageBucket: 'social-app-d5767.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJkG7-5I4kzEpyLGhYMCdvbgNl9MTYAE',
    appId: '1:144754486345:ios:b961187b331133e2d5a398',
    messagingSenderId: '144754486345',
    projectId: 'social-app-d5767',
    storageBucket: 'social-app-d5767.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSiM8TKzMB2P3-DftAqoShZA-FFiGXlEw',
    appId: '1:144754486345:web:8dbd07fd1169d9b9d5a398',
    messagingSenderId: '144754486345',
    projectId: 'social-app-d5767',
    authDomain: 'social-app-d5767.firebaseapp.com',
    storageBucket: 'social-app-d5767.firebasestorage.app',
  );
}
