// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQW3hdkWvkvmWYsCJyp5L-mpYTB3gYU8',
    appId: '1:93471930782:web:e0e12cc9e05920cf823e8f',
    messagingSenderId: '93471930782',
    projectId: 'loja-getx-firebase',
    authDomain: 'loja-getx-firebase.firebaseapp.com',
    storageBucket: 'loja-getx-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlNiDYAlGt8DU73kJdaBJMOpOb3eMVfuY',
    appId: '1:93471930782:android:3805718b3ae47ea6823e8f',
    messagingSenderId: '93471930782',
    projectId: 'loja-getx-firebase',
    storageBucket: 'loja-getx-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAal50Ji9q-vISvHv4kWFGQdITwl2irrns',
    appId: '1:93471930782:ios:9d539f7fe60256c9823e8f',
    messagingSenderId: '93471930782',
    projectId: 'loja-getx-firebase',
    storageBucket: 'loja-getx-firebase.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.lojaGetxFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAal50Ji9q-vISvHv4kWFGQdITwl2irrns',
    appId: '1:93471930782:ios:9d539f7fe60256c9823e8f',
    messagingSenderId: '93471930782',
    projectId: 'loja-getx-firebase',
    storageBucket: 'loja-getx-firebase.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.lojaGetxFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRQW3hdkWvkvmWYsCJyp5L-mpYTB3gYU8',
    appId: '1:93471930782:web:4fa2346a257c5828823e8f',
    messagingSenderId: '93471930782',
    projectId: 'loja-getx-firebase',
    authDomain: 'loja-getx-firebase.firebaseapp.com',
    storageBucket: 'loja-getx-firebase.firebasestorage.app',
  );
}
