// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm6ivp_pdAVWHPMFA5cDlBIdX_emg-q28',
    appId: '1:401093074757:web:599509d3e438510e9c282c',
    messagingSenderId: '401093074757',
    projectId: 'lista-de-tarefas-app-f7bca',
    authDomain: 'lista-de-tarefas-app-f7bca.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-app-f7bca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgVjUTYXBVpK0XNW4WHZ_kiZ03MuXpCBo',
    appId: '1:401093074757:android:6666724ff2fbce929c282c',
    messagingSenderId: '401093074757',
    projectId: 'lista-de-tarefas-app-f7bca',
    storageBucket: 'lista-de-tarefas-app-f7bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRGTNlK1Lh8aUzT-vbdTE3zmlqSb2N_o',
    appId: '1:401093074757:ios:af9e6e1c78c359af9c282c',
    messagingSenderId: '401093074757',
    projectId: 'lista-de-tarefas-app-f7bca',
    storageBucket: 'lista-de-tarefas-app-f7bca.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.todoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRGTNlK1Lh8aUzT-vbdTE3zmlqSb2N_o',
    appId: '1:401093074757:ios:af9e6e1c78c359af9c282c',
    messagingSenderId: '401093074757',
    projectId: 'lista-de-tarefas-app-f7bca',
    storageBucket: 'lista-de-tarefas-app-f7bca.firebasestorage.app',
    iosBundleId: 'br.com.luisa.dev.todoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm6ivp_pdAVWHPMFA5cDlBIdX_emg-q28',
    appId: '1:401093074757:web:8a828d7dace2aee19c282c',
    messagingSenderId: '401093074757',
    projectId: 'lista-de-tarefas-app-f7bca',
    authDomain: 'lista-de-tarefas-app-f7bca.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-app-f7bca.firebasestorage.app',
  );
}
